project:
  type: website

website:
  title: "COVID-19 Testing Analysis"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rasw0001
format:
  html:
    theme: sandstone
    css: styles.css



